language: node_js
node_js:
  - "10.15.3"
script:
  - npm run lint
  - npm run test
deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "QaYZuY/4+LNFc2aEqUnflPrQkB3BNVTkl+rPZsppQbWUYHjOPFCspYceFJfGffLZsJL2mg7Abze138a/pIP5KCngHH4aXzDoE6YGJFHa2Sz17izFNzjO76bmg5SOhIj4ffLWlcDVAK/vbrmuRVLNkLLTCHiu7FDzxtHUl/wPaf1syeU7MgziMzH/+KUraSVoyTGOWpnLG2pQEbXJ+P9fvKVePEc7CA9W4jk5+SbfTEcQ+m6CgZ7tRNdqYgHaI50Fu1buQNkZssOX6jz/+eTOxPrF168CNsYJd8fEmZ6WYZqEy+4hIKXyxEkSZ0xqNLI+YvzL+L26+pUxXLajbj7W4aXlcdfYsYgStwkubMRIcY98AR/hgovKJ68EtHP3/uxKnSBLK7lnQOYegFVgBtI3Nv2nl9BY52w+Y7J6jczbQMkb2YwrnStk8V+cUPnK5F/O/wL8RkdUQkloILrcbFWUORy862sCXlGRSsiwWzXaoPrP7YEtH2SwQ3GDwhmnSSqENIpkSzhvJcBaFlPKxwGRo9dClEcCZqydEdf/oE3z8hvb+vSXNvYikRlQPvrjKkIvfi8xHShCPVuOVQ3TwCbWrVVwSGvYx7zgy+Y9ypbMSbhtED8SH5r1OPeUQuEUn6YRfOXAzqST08qLilwPiZdnkcGCxk6a8j97qvsW12/b28o="
  secret_access_key:
    secure: "Rgciws4hbyb2Yzs3ssm8j51hBj2lWGIdZWp64ybLIwJ4WOR/AKaNEyD6bNIXcHsUPtRSKK0nwQ6ADI6qPBmefr7yaTn3cf1RNtqoIqPors967xum3xcJVJ4TDN6I0VUAX1K0eKzSOlqgs1XrhcyFWCMSZgms3WHpLuv62JUTmw7MCjz4zLgXfbuspsh0xnOGbC217BbgSTAaQmUZTvXwkdV/NpAIhXp1z5qP0LX2SNL1nGxvfKd4bA7tZXIvf0sbisAgq5oVAZjDBXX6WL1Mf1og//4IGhQuEF3fKYSwobqB6ygQPMm6ZPYA/Bd/wdm0/TQXHyhf713jnNMSwB4mqABWLqSoZBugjPVlUrSwo/6Iz2zzQnwqCKLq8QJPd0dtAQanMhvkR8862BhktjAhqmDACCBoMDd1/QUZ9bCo2Y3ZDJzZ4t2jaHaRHgyeBxBM9xPpgz1LIYTnMAZxtwP2iPNq0IVSwgZn0okybEZKL+EG5Sd89h6RQKpiGBLt7HqcTqeShDcaUCN1uumw09/EliubHgmux03V5Vje9qD3dl+CoDwA/98dBOwWr3Fqzu7JxTD2yleTDhU+RpR3kcYhLov229shpPBdjdtuk5PjMIgzJDaqS0IWbjMEzTxivTTBfFSWv3bP20gFiAI9+zRcipiWQVsvYCMJhQ5nqd7lrv0="
  region: "us-east-1"  
  app: "lernt"
  env: "Lernt-Prod"
  bucket_name: "elasticbeanstalk-us-east-1-963617016332"