language: node_js
node_js:
  - "10.15.3"
script:
  - npm run build
  - npm run lint
  - npm run test
  - cd client && npm run start & && npm run cypress-run
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAI4Y2ZXNVRWF4GPVQ
  secret_access_key:
    secure: DYMj3eMelmdLY1OEcp8UdZFgge6OnVDwU+54VKlSrtdO7qDBQZspu2nZyCMFx/RIk+T3k80WzA2fTnxNLgs2n2zgcddfOtW+3pB+UyM4C+4LIqi6ApmF7l4wlXMc2HMbE5LWoVQ3/HseeXHWapsz1iYjLqUzufKFURK6rRFHZWFlu+Ez4mWuffFtMXkccyiMFqP7SKwTHr3Qw2w4nOjUOCKaAk2JRYkqSMOMIUBBlyxoaXVC1JLc7Q2IF9lFIDMec9XHlPKV22ncxMMgOz/lle5S2Fb0vDmH5k4bB4T01P5FyRKPz9XzYa/0pPqxFiKV9cs5M2p31MojvDinAGfFlLM36qTbrJWJLFPm7PbKg00rJ9UtXcFXVjNTmd8iutqm2GgOwRCkl/i6+AwEKmBJoy98RtfXbWigmUj35OUVZD05ULgcZ1BzQQHwmsI2Pp+paV7QdypzMdt+Mbr0CihNQxh8XyJIhxOwILW9Ik2BOo2aQKE+Dg2zAxzg7BGmmIBJCPQ0qgn+//WPP9fc9Vsm/stA4Y8/9rR2zPwDVb9DgsBkehByBVt7Ssd293otUShEW1GbFQ0mjtV3jRbCkrla0SzaoD8YRGYeST8zfJyxQ6yb2TSMwPxrozNr2Ou2I96velv9mEsC2RAuq/nOb1NkNRX9eP3JTb6EyKpEJ4HuJMU=
  region: us-east-1
  app: lernt
  env: prod
  bucket_name: elasticbeanstalk-us-east-1-963617016332
  on:
    repo: capstone-paths/app
    branch: master